services:
  asterisk:
    container_name: asterisk
    build:
      context: ./asterisk
      network: host
    network_mode: host
    privileged: true
    restart: always
  lldpd:
    container_name: lldpd
    build:
      context: ./lldpd
      network: host
    network_mode: host
    privileged: true    
    restart: always
