FROM debian:latest

RUN apt update

ADD https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-22-current.tar.gz asterisk.tar.gz

RUN tar -zxvf asterisk.tar.gz && \
	mv asterisk-* asterisk && \
	rm -f asterisk.tar.gz

WORKDIR /asterisk

RUN ./contrib/scripts/install_prereq install

RUN ./configure --with-pjproject-bundled  && \
	make -j$(nproc) && \
	make install

RUN make samples

WORKDIR /

COPY ./conf /etc/asterisk

COPY ./tools/ /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 5060/udp
EXPOSE 5060/tcp
EXPOSE 5061/tcp
EXPOSE 5061/udp
EXPOSE 10000-20000/udp

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["asterisk", "-f"]
